### ISSUE TITLE
[Jamie] 컬럼, 카드 렌더링

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/todo-list#10]
## 📃 Description

서버에서 데이터를 가져와 컬럼과 카드를 렌더링한다.

## ☑ Todo
- [x] `Column`, `Card` 컴포넌트 생성
- [x] 데이터를 저장할 스토어 생성
- [x] 서버에서 가져온 데이터를 스토어에 저장 후 컴포넌트 렌더링
