### ISSUE TITLE
[Jamie] 카드 삭제

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/todo-list#13]
## 📃 Description

버튼을 클릭하면 등록된 카드를 삭제할 것인지 묻는 alert 창이 뜨고, 삭제 버튼을 누르면 카드를 삭제한다.

## ☑ Todo
- [x] X 버튼에 마우스를 올리면 카드가 빨갛게 변한다.
- [x] alert 컴포넌트를 생성한다. 컴포넌트가 렌더링되면 뒤의 화면을 어둡게 바꿔준다.
- [x] X 버튼을 누르면 삭제 여부를 묻는 alert 창이 뜬다.
- [x] 취소 버튼을 누르면 alert 창이 닫힌다.
- [x] 삭제 버튼을 누르면 alert 창을 닫고 서버에 DELETE 요청을 보낸다.
- [x] 요청이 성공한 경우 카드 목록을 다시 렌더링한다.
