### ISSUE TITLE
[COMMON] 서버 및 렌더링 관련 리펙토링 ∙ 데이터 순서 처리

### ISSUE THREAD

**Issue by JinJeon** [mina-gwak/todo-list#17]
## 📃 Description
서버 로직 수정, 칼럼 전체 렌더링을 칼럼 뱃지 렌더링으로 수정, task에 order 속성 추가 및 처리

## ☑ Todo
- [x]  액션 컨텐츠 서버 로직 수정 - 서버에서는 관련 데이터만 저장하고 돔 생성은 프론트에서 하도록
- [x]  로직 변경 후 바뀐 데이터를 통해 렌더링
-  task 데이터 순서 변경 기능 추가 (task 데이터에 order 속성 추가)
    - [x] DELETE method 일 시(삭제 시) 데이터 삭제 및 order 속성 변경
    - [x] PATCH method 일 시(드래그앤드롭, 수정) 데이터 수정 또는 데이터 삭제 ∙ 추가
        - 순서만 변경되는 경우 order
        - 순서, 컬럼 모두 변경되는 경우 column, order
- [x] 추가, 삭제, 수정 요청 후 액션 데이터 업데이트 & 렌더링
