### ISSUE TITLE
[COMMON] PR 리뷰 반영

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/todo-list#18]
## 📃 Description

PR에서 피드백해주신 부분 수정

## ☑ Todo
- [x] babel-node 글로벌 설치
- [x] BASE_URL 위치 변경
- [x] requestWithoutJson 함수 수정 혹은 삭제
- [x] calculateTimeDiff 수정
