### ISSUE TITLE
[COMMON] 드래그앤드롭

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/todo-list#19]
## 📃 Description

요구사항 중 드래그 앤 드롭 기능을 구현

## ☑ Todo
- [x] 유저가 카드를 드래그하면 잔상이 생기고, 카드가 반투명해진 채로 마우스를 따라온다.
- [x] 이동 경로의 절반 정도가 되면 카드의 예정 목적지로 잔상이 먼저 이동한다.
- [x] 이동 후 드래그를 중단하면 카드는 잔상이 있던 위치로 이동하고 잔상은 사라진다.
- [x] 이동이 완료되면 서버에 카드의 위치를 수정하는 요청을 전송한다. (서버의 카드 순서 변경 로직 추가 후)
- [x] 요청이 성공적으로 끝나면 프론트에서 변경사항을 리렌더링한다.
