### ISSUE TITLE
[COMMON] 개발환경 설정

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/todo-list#3]
## 📃 Description
프로젝트의 개발 환경을 설정한다.

## ☑ Todo
- Webpack 설정
    - [x]  SCSS 변경 사항 즉시 적용
    - [x]  JS 파일에 Babel 설정
- package.json 설정
    - [x] nodemon 설정
    - [x]  sass 설정
- [x]  Prettier 설정
- [x]  `.gitignore` 설정
- [x] json-server 설정
- [x] 프로젝트 구조 설정
- [x] markup 작성 및 scss 구조 설정 ∙ 작성
