### ISSUE TITLE
[JinJeon] 칼럼 + 버튼 및 카드 등록 박스 이벤트 설정

### ISSUE THREAD

**Issue by JinJeon** [mina-gwak/todo-list#8]
## 📃 Description
칼럼 타이틀 옆 + 버튼을 누를 시 새로운 카드를 등록하는 박스 생성, 등록 완료 시 카드 목록 추가, 특정 조건에서 박스 사라짐 기능 구현

## ☑ Todo
- [x] + 버튼 마우스 올릴 시 버튼 색상 변경
- [x] + 버튼 클릭 시 카드 등록 박스 생성
- [x] 제목 ∙ 내용 모두 입력 시 등록 버튼 활성화
- [x] 등록 버튼 클릭 시 제목 ∙ 내용 서버로 전송
- [x] 서버에서 올바른 응답 시 카드 등록 박스 삭제
- [x] 생성된 카드를 목록에 추가
- [x] 카드 등록 박스 나타나있을 때 + 버튼 다시 클릭 시 박스 사라짐
- [x] 카드 등록 박스의 취소 버튼 클릭 시 박스 사라짐

## 💡 ETC
다른 스토리에 비해 구현 시간이 길어 추후 다른 팀원이 함께 작업 예정
