### ISSUE TITLE
[Jamie] 액션 레이어 생성

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/todo-list#9]
## 📃 Description

활동 기록을 보여주는 레이어를 생성하고, 서버에서 데이터를 받아와 렌더링한다.

## ☑ Todo

- [x] `json-server`에서 액션 데이터 가져오기
- [x] 액션 레이어 렌더링
- [x] 액션 데이터가 없을 경우 `활동 기록이 없습니다.`라는 문구 표시
- [x] 헤더의 메뉴 버튼, 레이어의 X 버튼 클릭했을 때 레이어 열고 닫기
- [x] 레이어 나타나고 사라질 때 트랜지션 적용
